### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by petermcd**
Added missing requirements.txt file

### CODE REVIEW

**Comment by petermcd** [comment]
fixes #2

**Comment by schuppentier** [comment]
Hi Peter,

thank you for the PR. You are right, the dependency declaration is missing here. Though I am not sure if a requirements.txt is correct here, as this is supposed to be used as a Package. According to https://python-packaging.readthedocs.io/en/latest/dependencies.html the `install_requires` in the setup.py would be the correct place for this. Do you want to update the PR?

**Comment by petermcd** [comment]
Hi sorry I am so used to using requirements.txt for the projects I work on, will correct the pr.

**Comment by petermcd** [comment]
Pull request has been updated as well as the commit message changed.

**Comment by schuppentier** [comment]
Alright, this looks good. Thank you!

**Pull request merged**
